"""added 'remarks' column in SalaryHistory model

Revision ID: 1e1641850d8c
Revises: b14cc80cbb26
Create Date: 2024-12-16 17:22:02.724171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1641850d8c'
down_revision = 'b14cc80cbb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_history', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
