"""refactored Employee and Salary history (formerly salary details) tables

Revision ID: b14cc80cbb26
Revises: f2d4b41d661d
Create Date: 2024-12-16 15:49:45.196690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14cc80cbb26'
down_revision = 'f2d4b41d661d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('allowance', sa.Float(), nullable=False),
    sa.Column('perks_allowance', sa.Float(), nullable=False),
    sa.Column('temp_ta', sa.Float(), nullable=False),
    sa.Column('pf', sa.Float(), nullable=False),
    sa.Column('net_total', sa.Float(), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('salary_details')
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], use_alter=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('employees_designation_id_fkey', type_='foreignkey')
        batch_op.drop_column('status_id')
        batch_op.drop_column('designation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('employees_designation_id_fkey', 'designations', ['designation_id'], ['id'])

    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('salary_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('basic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('allowance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('perks_allowance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('temp_ta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('provident_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gross', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='salary_details_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='salary_details_pkey')
    )
    op.drop_table('salary_history')
    # ### end Alembic commands ###
