"""fresh migration, versioned SalaryHistory

Revision ID: c04c065f86fc
Revises: 
Create Date: 2024-12-17 16:56:20.698697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04c065f86fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('designations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_history_version',
    sa.Column('employee_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('designation_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('basic', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('allowance', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('perks_allowance', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('temp_ta', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('pf', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('net_total', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('gross', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('employee_id', 'department_id', 'designation_id', 'status_id', 'transaction_id')
    )
    with op.batch_alter_table('salary_history_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_history_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_history_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_history_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('Probation', 'Confirmed', 'Scale Revised', name='status_types'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_types'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('emergency_contact', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('salary_history',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('allowance', sa.Float(), nullable=False),
    sa.Column('perks_allowance', sa.Float(), nullable=False),
    sa.Column('temp_ta', sa.Float(), nullable=False),
    sa.Column('pf', sa.Float(), nullable=False),
    sa.Column('net_total', sa.Float(), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'department_id', 'designation_id', 'status_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_history')
    op.drop_table('employees')
    op.drop_table('transaction')
    op.drop_table('statuses')
    with op.batch_alter_table('salary_history_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_history_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_salary_history_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_salary_history_version_end_transaction_id'))

    op.drop_table('salary_history_version')
    op.drop_table('employee_documents')
    op.drop_table('designations')
    op.drop_table('departments')
    # ### end Alembic commands ###
